"""
Docker SDK service — dynamically create / manage FL client containers.

The backend container must have /var/run/docker.sock mounted to talk to the
Docker daemon on the host.
"""

from __future__ import annotations

import logging
import os
import platform
from dataclasses import dataclass
from typing import Optional

import docker
from docker.errors import NotFound, APIError, ImageNotFound

from app.config import settings

log = logging.getLogger(__name__)


def _cert_name(client_id: str) -> str:
    """
    Convert a client_id to the cert filename prefix used by setup.sh / setup.ps1.

    setup.sh generates certs as   Bank_A.crt / Bank_A.key / Bank_A_ed25519.pem
    The convention is: each underscore-separated word is Title-cased.

    Examples:
        "bank_a"  → "Bank_A"
        "Bank_A"  → "Bank_A"   (already correct — idempotent)
        "bank_b"  → "Bank_B"
    """
    return "_".join(part.capitalize() for part in client_id.split("_"))


# ── Constants ────────────────────────────────────────────
FL_CLIENT_IMAGE = "iot-ids-fl-client:latest"
FL_SERVER_IMAGE = "iot-ids-fl-server:latest"
DOCKER_NETWORK = "iot_ids_network"
CONTAINER_PREFIX = "iot_ids_fl_client_"
FL_SERVER_CONTAINER = "iot_ids_fl_server"


# ── Container info DTO ───────────────────────────────────
@dataclass
class ContainerInfo:
    container_id: str
    name: str
    status: str  # created | running | paused | restarting | exited | dead
    image: str


# ── Lazy Docker client ──────────────────────────────────
_docker_client: Optional[docker.DockerClient] = None


def _get_docker() -> docker.DockerClient:
    """Return a cached Docker client (connects via /var/run/docker.sock)."""
    global _docker_client
    if _docker_client is None:
        _docker_client = docker.from_env()
    return _docker_client


# ── Public API ───────────────────────────────────────────

def create_client_container(
    client_id: str,
    data_path: str = "/app/data",
    *,
    fl_server_url: str | None = None,
    mode: str = "IDLE",
    auto_start: bool = False,
) -> ContainerInfo:
    """
    Create (but don't start) a Docker container for an FL client.

    Parameters
    ----------
    client_id   : Unique short id, e.g. "bank_a"
    data_path   : Path *inside the container* where data is mounted
    fl_server_url : Override FL server address (default from settings)
    mode        : Operating mode — IDLE | MONITOR | TRAIN
    auto_start  : Start the container immediately after creation

    Returns
    -------
    ContainerInfo with container_id, name, status, image
    """
    dk = _get_docker()
    container_name = f"{CONTAINER_PREFIX}{client_id.lower()}"

    # HOST_PROJECT_ROOT is the absolute path to the project on the *host*.
    # Since the backend runs inside Docker but talks to the host daemon via
    # the mounted socket, all volume source paths must be host-absolute.
    host_root = settings.HOST_PROJECT_ROOT

    # Normalise path separators — Docker on Windows still accepts forward slashes
    host_data_dir = os.path.join(host_root, "data", "clients", client_id.lower())
    host_fl_common = os.path.join(host_root, "fl_common")
    host_fl_client = os.path.join(host_root, "fl_client")
    host_model = os.path.join(host_root, "model")
    host_certs  = os.path.join(host_root, "certs")

    server_url = fl_server_url or f"{FL_SERVER_CONTAINER}:{settings.FL_SERVER_PORT}"

    # Phase 2 — mTLS + gradient signing paths inside the container
    # Cert filenames follow the convention generated by setup.sh / setup.ps1.
    container_cert_dir = "/app/certs"
    environment = {
        "CLIENT_ID": client_id,
        "FL_SERVER_URL": server_url,
        "DATA_PATH": data_path,
        "BACKEND_URL": "http://iot_ids_backend:8000",
        "MODE": mode.upper(),
        # mTLS client identity — cert files are named Bank_A.crt (Title_Case from setup.sh)
        "FL_CLIENT_CERT": f"{container_cert_dir}/{_cert_name(client_id)}.crt",
        "FL_CLIENT_KEY":  f"{container_cert_dir}/{_cert_name(client_id)}.key",
        "FL_CA_CERT":     f"{container_cert_dir}/ca.crt",
        # Ed25519 gradient signing key
        "CLIENT_SIGNING_KEY": f"{container_cert_dir}/{_cert_name(client_id)}_ed25519.pem",
    }

    volumes = {
        host_fl_client: {"bind": "/app", "mode": "rw"},
        host_fl_common: {"bind": "/fl_common", "mode": "rw"},
        host_data_dir:  {"bind": "/app/data", "mode": "ro"},
        host_model:     {"bind": "/app/models", "mode": "ro"},
        host_certs:     {"bind": container_cert_dir, "mode": "ro"},  # Phase 2 PKI
    }

    log.info("Creating container %s (image=%s)", container_name, FL_CLIENT_IMAGE)

    # Remove stale container with same name (if any)
    _remove_if_exists(container_name)

    container = dk.containers.create(
        image=FL_CLIENT_IMAGE,
        name=container_name,
        environment=environment,
        volumes=volumes,
        network=DOCKER_NETWORK,
        restart_policy={"Name": "no"},
        detach=True,
    )

    if auto_start:
        container.start()
        container.reload()

    return ContainerInfo(
        container_id=container.id,
        name=container.name,
        status=container.status,
        image=FL_CLIENT_IMAGE,
    )


def start_container(container_id: str) -> ContainerInfo:
    """Start a stopped container."""
    dk = _get_docker()
    container = dk.containers.get(container_id)
    container.start()
    container.reload()
    log.info("Started container %s (%s)", container.name, container.short_id)
    return _to_info(container)


def stop_container(container_id: str, timeout: int = 10) -> ContainerInfo:
    """Stop a running container."""
    dk = _get_docker()
    container = dk.containers.get(container_id)
    container.stop(timeout=timeout)
    container.reload()
    log.info("Stopped container %s (%s)", container.name, container.short_id)
    return _to_info(container)


def remove_container(container_id: str, force: bool = True) -> None:
    """Remove a container (force-kill if running)."""
    dk = _get_docker()
    try:
        container = dk.containers.get(container_id)
        log.info("Removing container %s (%s)", container.name, container.short_id)
        container.remove(force=force)
    except NotFound:
        log.warning("Container %s not found — already removed", container_id)


def get_container_status(container_id: str) -> ContainerInfo | None:
    """Get current status of a container. Returns None if not found."""
    dk = _get_docker()
    try:
        container = dk.containers.get(container_id)
        container.reload()
        return _to_info(container)
    except NotFound:
        return None


def list_containers(all: bool = True) -> list[ContainerInfo]:
    """List all FL client containers (matching our prefix)."""
    dk = _get_docker()
    containers = dk.containers.list(all=all, filters={"name": CONTAINER_PREFIX})
    return [_to_info(c) for c in containers]


def ensure_image_exists() -> bool:
    """
    Check that the FL client Docker image exists.
    Returns True if image is available.
    """
    dk = _get_docker()
    try:
        dk.images.get(FL_CLIENT_IMAGE)
        return True
    except ImageNotFound:
        log.warning(
            "FL client image '%s' not found. "
            "Run: docker build -t %s ./fl_client",
            FL_CLIENT_IMAGE,
            FL_CLIENT_IMAGE,
        )
        return False


# ── Data Validation ──────────────────────────────────────

def validate_client_data(client_id: str) -> bool:
    """
    Check if a client has training data (.npy files) in its data directory.
    The backend has client data mounted at /app/client_data/<client_id>/
    Returns True if at least one X_seq_chunk and y_seq_chunk file exist.
    """
    # Inside Docker container, client data is at /app/client_data/<id>/
    data_dir = os.path.join("/app", "client_data", client_id.lower())

    if not os.path.isdir(data_dir):
        log.warning("Data directory not found: %s", data_dir)
        return False

    files = os.listdir(data_dir)
    has_x = any(f.startswith("X_seq") and f.endswith(".npy") for f in files)
    has_y = any(f.startswith("y_seq") and f.endswith(".npy") for f in files)

    if not (has_x and has_y):
        log.warning("No training data in %s (X_seq: %s, y_seq: %s)", data_dir, has_x, has_y)
        return False

    return True


# ── FL Server Container Management ───────────────────────

def start_fl_server(
    *,
    num_rounds: int = 5,
    min_clients: int = 1,
    use_he: bool = False,
    client_names: list[str] | None = None,
) -> ContainerInfo:
    """
    Create and start the FL server container.

    Removes any existing server container first to ensure clean state.
    client_names: list of client_id strings to pass as the CLIENTS env var so
    the FL server knows which clients to expect (VSS ceremony, trust scores).
    """
    dk = _get_docker()
    host_root = settings.HOST_PROJECT_ROOT

    host_fl_server = os.path.join(host_root, "fl_server")
    host_fl_common = os.path.join(host_root, "fl_common")
    host_model = os.path.join(host_root, "model")
    host_certs  = os.path.join(host_root, "certs")

    container_cert_dir = "/app/certs"
    environment = {
        "ROUNDS": str(num_rounds),
        "MIN_CLIENTS": str(min_clients),
        "MIN_FIT_CLIENTS": str(min_clients),
        "USE_HE": "true" if use_he else "false",
        "FL_SERVER_ADDRESS": "0.0.0.0:8080",
        "BACKEND_URL": "http://iot_ids_backend:8000",
        # Phase 2 — mTLS server credentials
        "FL_TLS_CERT": f"{container_cert_dir}/server.crt",
        "FL_TLS_KEY":  f"{container_cert_dir}/server.key",
        "FL_TLS_CA":   f"{container_cert_dir}/ca.crt",
        # Phase 2 — client Ed25519 public keys for gradient signature verification
        "CLIENT_KEY_DIR": f"{container_cert_dir}/client_keys/",
        # Canvas-driven: comma-separated list of client_id values to train
        "CLIENTS": ",".join(client_names) if client_names else "",
    }

    volumes = {
        host_fl_server: {"bind": "/app", "mode": "rw"},
        host_fl_common: {"bind": "/fl_common", "mode": "rw"},
        host_model:     {"bind": "/app/models", "mode": "rw"},
        host_certs:     {"bind": container_cert_dir, "mode": "ro"},  # Phase 2 PKI
    }

    log.info("Starting FL server container (rounds=%d, clients=%d, HE=%s)",
             num_rounds, min_clients, use_he)

    _remove_if_exists(FL_SERVER_CONTAINER)

    container = dk.containers.create(
        image=FL_SERVER_IMAGE,
        name=FL_SERVER_CONTAINER,
        environment=environment,
        volumes=volumes,
        network=DOCKER_NETWORK,
        ports={"8080/tcp": 8080},
        restart_policy={"Name": "no"},
        detach=True,
    )

    # Add network alias so clients can reach it as "fl_server" (docker-compose service name)
    try:
        network = dk.networks.get(DOCKER_NETWORK)
        network.disconnect(container)
        network.connect(container, aliases=["fl_server", FL_SERVER_CONTAINER])
    except Exception as exc:
        log.warning("Failed to set network alias for FL server: %s", exc)

    container.start()
    container.reload()

    return _to_info(container)


def stop_fl_server() -> None:
    """Stop and remove the FL server container."""
    dk = _get_docker()
    try:
        container = dk.containers.get(FL_SERVER_CONTAINER)
        container.stop(timeout=10)
        container.remove(force=True)
        log.info("FL server container stopped and removed")
    except NotFound:
        log.warning("FL server container not found")


def get_fl_server_status() -> ContainerInfo | None:
    """Get FL server container status."""
    dk = _get_docker()
    try:
        container = dk.containers.get(FL_SERVER_CONTAINER)
        container.reload()
        return _to_info(container)
    except NotFound:
        return None


# ── Persistent Container Lifecycle ───────────────────────

def get_container_by_name(name: str) -> "docker.models.containers.Container | None":
    """
    Return the Docker container object (running or stopped) by exact name.
    Returns None if no container with that name exists.
    """
    dk = _get_docker()
    containers = dk.containers.list(all=True, filters={"name": f"^{name}$"})
    return containers[0] if containers else None


def ensure_client_container_running(
    client_id: str,
    data_path: str,
    mode: str = "IDLE",
) -> ContainerInfo:
    """
    Guarantee that a persistent container named
    ``iot_ids_fl_client_<client_id_lower>`` is running in the given mode.

    - If already running in the correct mode  → return its info (no-op).
    - If running in the wrong mode            → stop, remove, recreate.
    - If stopped / exited                     → remove, recreate.
    - If missing entirely                     → create and start.
    """
    name = f"{CONTAINER_PREFIX}{client_id.lower()}"
    existing = get_container_by_name(name)

    if existing:
        existing.reload()
        if existing.status == "running":
            # Check whether the MODE env var matches
            env_list: list[str] = existing.attrs.get("Config", {}).get("Env") or []
            current_mode = None
            for entry in env_list:
                if entry.startswith("MODE="):
                    current_mode = entry.split("=", 1)[1]
                    break
            if current_mode == mode.upper():
                log.info(
                    "Container %s already running in mode %s — no-op",
                    name, mode.upper(),
                )
                return get_container_status(existing.id)  # type: ignore[return-value]
            else:
                log.info(
                    "Container %s running in mode %s, need %s — recreating",
                    name, current_mode, mode.upper(),
                )
                stop_container(existing.id)
                remove_container(existing.id)
        else:
            # Stopped / exited / created — just remove and recreate
            log.info(
                "Container %s exists but is %s — removing and recreating",
                name, existing.status,
            )
            remove_container(existing.id)

    # Container absent or just removed — create fresh in the requested mode
    return create_client_container(
        client_id=client_id,
        data_path=data_path,
        fl_server_url="",
        mode=mode,
        auto_start=True,
    )


def update_client_container_mode(
    client_id: str,
    data_path: str,
    new_mode: str,
) -> ContainerInfo:
    """
    Transition a persistent client container to a new MODE without destroying
    the logical "slot".  The sequence is:

    1. Stop the running container (if running).
    2. Remove it.
    3. Recreate and start with ``new_mode``.

    Used to toggle IDLE → TRAIN at training start and TRAIN → IDLE at
    training end / stop.
    """
    name = f"{CONTAINER_PREFIX}{client_id.lower()}"
    existing = get_container_by_name(name)

    if existing:
        existing.reload()
        if existing.status == "running":
            log.info("Stopping container %s before mode change to %s", name, new_mode)
            stop_container(existing.id)
        log.info("Removing container %s before recreating in mode %s", name, new_mode)
        remove_container(existing.id)

    return create_client_container(
        client_id=client_id,
        data_path=data_path,
        fl_server_url="",
        mode=new_mode,
        auto_start=True,
    )


# ── Helpers ──────────────────────────────────────────────

def _to_info(container) -> ContainerInfo:
    """Convert a docker container object to our DTO."""
    return ContainerInfo(
        container_id=container.id,
        name=container.name,
        status=container.status,
        image=str(container.image.tags[0]) if container.image.tags else "unknown",
    )


def _remove_if_exists(name: str) -> None:
    """Remove a container by name if it exists (cleanup stale runs)."""
    dk = _get_docker()
    try:
        old = dk.containers.get(name)
        old.remove(force=True)
        log.info("Removed stale container %s", name)
    except NotFound:
        pass
