"""initial_tables

Revision ID: 422eeb5b1f9f
Revises: 
Create Date: 2026-02-08 12:41:54.316361
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '422eeb5b1f9f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('device_type', sa.Enum('camera', 'sensor', 'gateway', 'actuator', 'smart_plug', 'custom', name='device_type_enum', create_constraint=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('protocol', sa.Enum('mqtt', 'coap', 'http', 'tcp', 'udp', name='protocol_enum'), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('online', 'offline', 'quarantined', 'under_attack', name='device_status_enum'), nullable=False),
    sa.Column('traffic_source', sa.Enum('live_capture', 'pcap_upload', 'simulated', name='traffic_source_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('threat_count_today', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_name'), 'devices', ['name'], unique=True)
    op.create_table('fl_client_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=50), nullable=False),
    sa.Column('local_loss', sa.Float(), nullable=False),
    sa.Column('local_accuracy', sa.Float(), nullable=False),
    sa.Column('num_samples', sa.Integer(), nullable=False),
    sa.Column('training_time_sec', sa.Float(), nullable=False),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fl_client_metrics_round_id'), 'fl_client_metrics', ['round_id'], unique=False)
    op.create_table('fl_clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'training', name='fl_client_status_enum'), nullable=False),
    sa.Column('data_path', sa.String(length=500), nullable=False),
    sa.Column('container_id', sa.String(length=100), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fl_clients_client_id'), 'fl_clients', ['client_id'], unique=True)
    op.create_table('fl_rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('num_clients', sa.Integer(), nullable=False),
    sa.Column('global_loss', sa.Float(), nullable=True),
    sa.Column('global_accuracy', sa.Float(), nullable=True),
    sa.Column('global_f1', sa.Float(), nullable=True),
    sa.Column('global_precision', sa.Float(), nullable=True),
    sa.Column('global_recall', sa.Float(), nullable=True),
    sa.Column('aggregation_method', sa.String(length=50), nullable=False),
    sa.Column('he_scheme', sa.String(length=20), nullable=True),
    sa.Column('he_poly_modulus', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('model_checkpoint_path', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_number')
    )
    op.create_table('predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('traffic_log_id', sa.BigInteger(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('label', sa.Enum('benign', 'attack', name='prediction_label_enum', create_constraint=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('attack_type', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('window_start_idx', sa.BigInteger(), nullable=True),
    sa.Column('window_end_idx', sa.BigInteger(), nullable=True),
    sa.Column('feature_importance', sa.JSON(), nullable=True),
    sa.Column('inference_latency_ms', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_device_id'), 'predictions', ['device_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'operator', 'viewer', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_predictions_device_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('fl_rounds')
    op.drop_index(op.f('ix_fl_clients_client_id'), table_name='fl_clients')
    op.drop_table('fl_clients')
    op.drop_index(op.f('ix_fl_client_metrics_round_id'), table_name='fl_client_metrics')
    op.drop_table('fl_client_metrics')
    op.drop_index(op.f('ix_devices_name'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
